[workspace]

[package]
name = "emu6502_web"
description = "Apple ][+/2e Emulator in Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emu6502 = { path = "../emulator" }
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.32"
js-sys = "0.3.59"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1.7"
once_cell = "1.13.0"
wee_alloc = "0.4.5"
autocfg = "1.1.0"

[lib]
name = "emu6502_web"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

